const k = (n) => n * 1000;

export const formatKip = (n) => `₭${n.toLocaleString("en-US")}`;

export const MENU_TABS = [
  { id: "all", label: "All" },
  { id: "coffee", label: "Coffee" },
  { id: "tea", label: "Tea & Specials" },
  { id: "soda", label: "Soda" },
  { id: "shake", label: "Shakes & Juice" },
];

export const MENU = [
  { id: "americano", name: "Americano", lao: "ອາເມຣິກາໂນ", category: "coffee", image: "assets/menu-espresso.jpg",
    variants: [{ label: "Hot", price: k(40) }, { label: "Ice", price: k(40) }] },
  { id: "latte", name: "Latte", lao: "ລາເຕ້", category: "coffee", image: "assets/menu-latte.jpg",
    variants: [{ label: "Hot", price: k(45) }, { label: "Ice", price: k(55) }, { label: "Shake", price: k(65) }] },
  { id: "cappuccino", name: "Cappuccino", lao: "ຄາປູຊີໂນ", category: "coffee", image: "assets/menu-cappuccino.jpg",
    variants: [{ label: "Hot", price: k(42) }, { label: "Ice", price: k(50) }, { label: "Shake", price: k(65) }] },
  { id: "espresso", name: "Espresso", lao: "ເອສເພຣສໂຊ", category: "coffee", image: "assets/menu-espresso.jpg",
    variants: [{ label: "Hot", price: k(35) }, { label: "Ice", price: k(50) }, { label: "Shake", price: k(55) }] },
  { id: "mocha", name: "Mocha", lao: "ມັອກກ້າ", category: "coffee", image: "assets/menu-latte.jpg",
    variants: [{ label: "Hot", price: k(50) }, { label: "Ice", price: k(59) }, { label: "Shake", price: k(69) }] },
  { id: "flat-white", name: "Flat White", lao: "ແຟຼດໄວ", category: "coffee", image: "assets/menu-cappuccino.jpg",
    variants: [{ label: "Hot", price: k(40) }, { label: "Ice", price: k(50) }] },
  { id: "vanilla-latte", name: "Vanilla Latte", lao: "ວານິລາ ລາເຕ້", category: "coffee", image: "assets/menu-latte.jpg",
    variants: [{ label: "Hot", price: k(50) }, { label: "Ice", price: k(58) }] },
  { id: "caramel-latte", name: "Caramel Latte", lao: "ຄາຣາແມວ ລາເຕ້", category: "coffee", image: "assets/menu-latte.jpg",
    variants: [{ label: "Hot", price: k(50) }, { label: "Ice", price: k(58) }, { label: "Shake", price: k(75) }] },
  { id: "hazelnut-cappuccino", name: "Hazelnut Cappuccino", lao: "ເຮເຊວນັດ ຄາປູຊີໂນ", category: "coffee", image: "assets/menu-cappuccino.jpg",
    variants: [{ label: "Hot", price: k(50) }, { label: "Ice", price: k(58) }] },
  { id: "espresso-macchiato", name: "Espresso Macchiato", lao: "ເອສເພຣສໂຊ ມັກກິອາໂຕ", category: "coffee", image: "assets/menu-espresso.jpg",
    variants: [{ label: "Hot", price: k(45) }] },
  { id: "cold-brew", name: "Cold Brew", lao: "ໂຄນບຣິວ", category: "coffee", image: "assets/menu-espresso.jpg",
    variants: [{ label: "Ice", price: k(65) }] },
  { id: "drip-coffee", name: "Drip Coffee", lao: "ກາເຟຢົດ", category: "coffee", image: "assets/menu-espresso.jpg",
    variants: [{ label: "Hot", price: k(65) }, { label: "Ice", price: k(65) }],
    description: "Catimor, Typica, Ethiopia, Robusta, Catuai, Costa Rica, Java." },
  { id: "green-tea", name: "Green Tea", lao: "ຊາຂຽວ", category: "tea", image: "assets/gallery-1.jpg",
    variants: [{ label: "Hot", price: k(60) }, { label: "Ice", price: k(65) }, { label: "Shake", price: k(75) }] },
  { id: "chocolate", name: "Chocolate", lao: "ຊ໋ອກໂກແລັດ", category: "tea", image: "assets/menu-cheesecake.jpg",
    variants: [{ label: "Hot", price: k(50) }, { label: "Ice", price: k(57) }, { label: "Shake", price: k(65) }] },
  { id: "milk-tea", name: "Milk Tea", lao: "ຊານົມ", category: "tea", image: "assets/gallery-1.jpg",
    variants: [{ label: "Ice", price: k(57) }] },
  { id: "milk", name: "Milk", lao: "ນົມ", category: "tea", image: "assets/gallery-2.jpg",
    variants: [{ label: "Hot", price: k(50) }, { label: "Ice", price: k(55) }, { label: "Shake", price: k(59) }] },
  { id: "lemon-tea", name: "Lemon Tea", lao: "ຊາໝາກນາວ", category: "tea", image: "assets/gallery-1.jpg",
    variants: [{ label: "Hot", price: k(45) }, { label: "Ice", price: k(50) }] },
  { id: "honey-lemon", name: "Honey Lemon", lao: "ນ້ຳເຜິ້ງໝາກນາວ", category: "tea", image: "assets/gallery-1.jpg",
    variants: [{ label: "Hot", price: k(45) }, { label: "Ice", price: k(50) }] },
  { id: "hot-tea", name: "Hot Tea Selection", lao: "ຊາຮ້ອນ", category: "tea", image: "assets/gallery-1.jpg",
    variants: [{ label: "Hot", price: k(55) }],
    description: "Green tea, Black tea, Butterfly pea tea, Dilmah tea." },
  { id: "black-honey-lemon", name: "Black Honey Lemon", lao: "ກາເຟດຳ ນ້ຳເຜິ້ງ", category: "coffee", image: "assets/menu-espresso.jpg",
    variants: [{ label: "Ice", price: k(57) }] },
  { id: "black-soda", name: "Black Soda", lao: "ກາເຟດຳ ໂຊດາ", category: "coffee", image: "assets/menu-espresso.jpg",
    variants: [{ label: "Ice", price: k(50) }] },
  { id: "black-orange", name: "Black Orange Juice", lao: "ກາເຟດຳ ນ້ຳສົ້ມ", category: "coffee", image: "assets/menu-espresso.jpg",
    variants: [{ label: "Ice", price: k(65) }] },
  { id: "lemon-soda", name: "Lemon Soda", lao: "ໂຊດາ ໝາກນາວ", category: "soda", image: "assets/gallery-2.jpg",
    variants: [{ label: "Ice", price: k(45) }] },
  { id: "raspberry-soda", name: "Raspberry Soda", lao: "ໂຊດາ ຣາສເບີຣີ", category: "soda", image: "assets/gallery-2.jpg",
    variants: [{ label: "Ice", price: k(45) }] },
  { id: "strawberry-soda", name: "Strawberry Soda", lao: "ໂຊດາ ສະຕຣໍເບີຣີ", category: "soda", image: "assets/gallery-2.jpg",
    variants: [{ label: "Ice", price: k(45) }] },
  { id: "passion-soda", name: "Passion Fruit Soda", lao: "ໂຊດາ ໝາກສະຕາ", category: "soda", image: "assets/gallery-2.jpg",
    variants: [{ label: "Ice", price: k(45) }] },
  { id: "peach-soda", name: "Peach Soda", lao: "ໂຊດາ ໝາກພິສ", category: "soda", image: "assets/gallery-2.jpg",
    variants: [{ label: "Ice", price: k(45) }] },
  { id: "blue-lemon-soda", name: "Blue Lemon Soda", lao: "ໂຊດາ ບລູເລມອນ", category: "soda", image: "assets/gallery-2.jpg",
    variants: [{ label: "Ice", price: k(45) }] },
  { id: "mango", name: "Mango", lao: "ໝາກມ່ວງ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Shake", price: k(40) }] },
  { id: "melon", name: "Melon", lao: "ແຕງດອມ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Shake", price: k(50) }] },
  { id: "orange-juice", name: "Orange Juice", lao: "ນ້ຳໝາກກ້ຽງ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Single", price: k(43) }] },
  { id: "watermelon", name: "Watermelon", lao: "ໝາກໂມ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Shake", price: k(40) }] },
  { id: "apple", name: "Apple", lao: "ແອັບເປິ້ນ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Shake", price: k(50) }] },
  { id: "banana", name: "Banana", lao: "ໝາກກ້ວຍ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Shake", price: k(40) }] },
  { id: "strawberry-banana", name: "Strawberry Banana", lao: "ສະຕຣໍ ໝາກກ້ວຍ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Shake", price: k(65) }] },
  { id: "banana-almond", name: "Banana Almond", lao: "ໝາກກ້ວຍ ອັນມອນ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Shake", price: k(65) }] },
  { id: "strawberry-milk", name: "Strawberry Milk", lao: "ສະຕຣໍ ນົມ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Shake", price: k(57) }] },
  { id: "strawberry-yogurt", name: "Strawberry Yogurt", lao: "ສະຕຣໍ ໂຍເກີດ", category: "shake", image: "assets/menu-donut.jpg",
    variants: [{ label: "Shake", price: k(75) }] },
  { id: "croissant", name: "Croissant", lao: "ຄຣົວຊອງ", category: "tea", image: "assets/menu-croissant.jpg",
    description: "72-hour laminated French butter, baked daily.",
    variants: [{ label: "Single", price: k(35) }] },
];
